### ISSUE TITLE
Following parameter references

### ISSUE THREAD

**Issue by aegershman** [openrewrite/rewrite-concourse#2]
In order to update key-values which are resolved indirectly as parameter references, we'll need a way to "follow" parameter references to update them without updating the original parameter.

For example, if we wanted to update the `source.uri` of the `git` resource named `code`, we'd want to make sure it's resolved parameter, `((github-repo))`, is updated. This may have multiple layers of indirection:

```yml
---
# pipeline.yml
resources:
- name: code
  type: git
  source:
    uri: ((github-repo))
...
---
# params0.yml
github-repo: ((indirect-repo))
...
---
# params1.yml
indirect-repo: https://github.com/openrewrite/rewrite-concourse
```

We do not want to change the original value when it is parameterized.
